### ISSUE TITLE
miss-typo in run_vm.sh

### ISSUE THREAD

**Issue by ParkHanbum** [ememos/Tutorial#8]
at the line 9 in run_vm.sh
```
# Default MEM_SIZE is half of total memory(MB).
MEM_SIZE=$(grep MemTotal /proc/meminfo | awk '{print $2}')
MEM_SZIE=$(( MEM_SIZE/2048 ))
```

As you can see, 'MEM_SIZE' was miss typed as 'MEM_SZIE'.

**Comment by YWHyuk** [comment]
Oops, It's my mistake. Using the default MEM_SIZE will cause error. 
Can you fix it and pull-request?
